### PR TITLE
Js2 feedbacks

### PR DESCRIPTION
**Pull request by Gonlonge**
I think all the required features is working now please check if anything is missing. I will use my time to remove all the console comments and improve my styling in the meanwhile

### CODE REVIEW

**Comment by asimenstad** [comment]
I like the look of the profile page, but since it's hardcoded I can’t see my own profile information. On the post feed I think it would be nice to be able to see the author and the time the post was created. Also there is edit and delete buttons on all of the posts and not just my own posts.

**Comment by Fermain** [comment]
Bug - you can click "Edit" & "Delete" on someone else's post. This should only be available for my posts. This results in a `403 Forbidden` error.

**Comment by Fermain** [comment]
Bug - Profile data is hardcoded, should reflect my data. The most common approach here is to store this in localStorage.

**Comment by Fermain** [comment]
Missing Functionality - Profile create post does not send a request. This is present on the homepage, so you have the code for it. Unfinished features should not be exposed to the user.

**Comment by Fermain** [comment]
Bug - Comment functionality not present, if something is unfinished it should not be exposed to the user.

**Comment by Fermain** [comment]
Missing Functionality - Cannot update profile media. The brief requests a form to update avatar/banner image URLs.

**Comment by Gonlonge** [comment]
Thank you for the feedback, I have now improved it.

**Pull request merged**
